### ISSUE TITLE
Can't customize the Preview Page

### ISSUE THREAD

**Issue by tosbatti** [nuxt-community/prismic-module#100]
As described in the [documentation](https://prismic.nuxtjs.org/previews#customizing-the-preview-page) I'm trying to customize the preview page, but seems to be always invoked the "built-in" page of the module (`src/templates/pages/preview.vue`).

I tried these paths (from project root):
- `prismic/pages/preview.vue`
- `app/prismic/pages/preview.vue`

Doc says `~/app/prismic/pages/preview.vue`, and it wasn't clear to me which one was correct.
Anyway, none of these seem to work.

**Comment by lihbr** [comment]
Hi @tosbatti, thanks for your contribution!

Nice catch, indeed I noticed that the module doesn't take that into account anymore 🤔 : https://github.com/nuxt-community/prismic-module/blob/master/src/index.js#L21-L24 like it does for link resolver & html serializer: https://github.com/nuxt-community/prismic-module/blob/master/src/index.js#L51-L69

Correct path should be `app/prismic/pages/preview.vue` (2nd one)

That's definitely an issue! If you feel like submitting a PR that's more than welcome ☺️

**Comment by lorenaramonda** [comment]
Hi @lihbr ,

could it be because the other two have a check:

this.addTemplate({
    fileName: 'prismic/link-resolver.js',
    **src: userLinkResolverExists ? userLinkResolver : path.join(__dirname, 'templates/link-resolver.js'),**
    options,
  });
  this.addTemplate({
    fileName: 'prismic/html-serializer.js',
    **src: fs.existsSync(userHtmlSerializer) ? userHtmlSerializer : path.join(__dirname, 'templates/html-serializer.js'),**
    options,
  });

while the vue file not?

**Comment by lihbr** [comment]
Hi @lorenaramonda, that's exactly that ☺️ The others check for existence of the file and conditionally use it while this one doesn't.

**Comment by lihbr** [comment]
Released in 1.2.4 🙂 #102
