### ISSUE TITLE
Closing Preview toolbar does not close it

### ISSUE THREAD

**Issue by cbaxter713** [nuxt-community/prismic-module#104]
I have @nuxtjs/prismic setup up and working as expected.  However, when I preview a document in my application, and then I try to "turn off" preview mode by clicking the X on the purple preview toolbar, preview mode never goes away.  The only way for me to get out of preview mode is to go into my cookies and delete the prismic preview cookies.

I would expect the preview mode to be removed by closing the X button, however this never happens.
![Screen Shot 2020-09-23 at 10 42 33 AM](https://user-images.githubusercontent.com/6816493/94043145-b4917580-fd89-11ea-82d6-3bcce04d1caf.png)

**Comment by lluishi93** [comment]
+1

**Comment by lihbr** [comment]
Hey, I'm really sorry for the lack of support back then! The toolbar has since gone through a lot of fixes related to that kind of issue (due to privacy policy updates and cookies messing), feel free to open another issue if you're still experiencing it!
