### ISSUE TITLE
Can't setup local dev environment to retrieve drafts

### ISSUE THREAD

**Issue by lluishi93** [nuxt-community/prismic-module#105]
Hi,

Is there any way to setup nuxtjs prismic module to retrieve all drafts, like Contentful preview API? The preview mode only allows to see the drafts of that specific Document. I tried looking for something like this in documentation but haven't found anything. Could someone help me out a bit?

Thanks.

**Comment by lihbr** [comment]
Hey @lluishi93, thanks for reaching out!

Currently, Prismic does not offer a "vanilla" preview API like Contentful, although that's something we're aware some of our users would like to see and we are considering implementing it.

However, you can still preview multiple documents at once by having them in a release and then preview the release as a whole ☺️ The video here shows you how to do so: https://user-guides.prismic.io/en/articles/778332-preview-releases
