### ISSUE TITLE
Support the new target: "static"

### ISSUE THREAD

**Issue by francois2metz** [nuxt-community/prismic-module#111]
The target "static" has been introduced in nuxt 1.13. It would be nice if prismic-module would support it.

Right now, using the static target, there is one call to the prismic api in the generated site:
https://github.com/nuxt-community/prismic-module/blob/c824747c3e90634324236d897097da11e7a2d831/src/templates/plugins/prismic.js#L19

**Comment by lihbr** [comment]
Closing in favor of #134

tl;dr; we'll consider switching to the `.client` method
