### ISSUE TITLE
Preview not working in SSR

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [nuxt-community/prismic-module#115]
Hi,

In nuxt ssr true this doesn't work for my project 

Here is my prismic code
```
prismic: {
    endpoint: 'https://my-repo.cdn.prismic.io/api/v2',
    linkResolver: '@/plugins/link-resolver',
    htmlSerializer: '@/plugins/html-serializer',
    preview: '/preview'
    /* see configuration for more */
  },
```

Error in console 

`Access to XMLHttpRequest at 'https://my-repo.cdn.prismic.io/api/v2/documents/search?page=1&pageSize=1&ref=https%3A%2F%2Fmy-repo.prismic.io%2Fpreviews%2FYAGwfBEAACMAgZ45%3AYAGzWREAACAAgaup%3FwebsitePreviewId&lang=*&q=%5B%5Bat(document.id%2C%20%22X_2fHxEAACEAbu1Q%22)%5D%5D' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by lihbr** [comment]
Hey @rahulkumarsingh73690, thanks for the report!

Can you provide an example component making a call to Prismic you're doing in your application? GET request shouldn't trigger CORS 🤔 Perhaps you're using GraphQL? Looking forward to helping on that ☺️

**Comment by rahulkumarsingh73690** [comment]
```
 <template>
  <p>Loading Prismic preview...</p>
</template>

<script>
export default {
  layout: 'blog',
  mounted() {
    this.$prismic.preview()
  },
}
</script>
```

**Comment by lihbr** [comment]
Ok I see, can you also provide a regular page component please ?

**Comment by rahulkumarsingh73690** [comment]
What do you mean by regular page component. you mean layout (blog)??

**Comment by lihbr** [comment]
Oh sorry, perhaps `~/pages/index.js` or `~/pages/blog/_slug.vue` yes! A component where you use `asyncData` or `fetch` basically :)

**Comment by rahulkumarsingh73690** [comment]
`~/pages/blog/_slug.vue
`
```
async asyncData({ $prismic, params, error }) {
    try {
      // Query post
      const post = await $prismic.api.getByUID('post', params.uid)
      // Get Meta Data
      // Get Meta Data
      const metadata = CreateMetadata(post)

      // Query related posts
      const relatedposts = await $prismic.api.query(
        [
          $prismic.predicates.similar(post.id, 6),
          $prismic.predicates.at('document.type', 'post'),
        ],
        { pageSize: 2 }
      )
      // Returns data to be used in template
      return {
        title: post.data.title,
        date: Intl.DateTimeFormat('en-US').format(
          new Date(post.first_publication_date)
        ),
        mainimage: post.data.image,
        slices: post.data.body,
        metadata: metadata,
        relatedposts: relatedposts.results,
      }
    } catch (e) {
      console.log(e)
      // Returns error page
      error({ statusCode: 404, message: 'Page not found' })
    }
  },
```

`~/pages/index.vue`

```
 async asyncData({ $prismic, error }) {
    try {
      // Query last posts
      const posts = await $prismic.api.query(
        $prismic.predicates.at('document.type', 'post'),
        {
          orderings: '[document.first_publication_date desc]',
          pageSize: 9,
        }
      )
      // Returns data to be used in template
      return {
        posts: posts.results,
      }
    } catch (e) {
      // Returns error page
      error({ statusCode: 404, message: 'Page not found' })
    }
  },
```

**Comment by lihbr** [comment]
Thank you very much! Nothing special here to notice, may I ask you what browser/version are you using?

**Comment by rahulkumarsingh73690** [comment]
> Thank you very much! Nothing special here to notice, you're doing it great! May I ask you what browser/version are you using?

Chrome and VS code

**Comment by lihbr** [comment]
Thanks again! Nothing related to the browser here. 🤔 Starting to get a bit clueless!

Can you try monitoring XHR requests in the network tab of the devtool? Trying to identify which request fails, sharing its method (GET/POST/etc.), request/response headers and status would be helpful! Might sound a bit daunting, if you want to I'm happy to jump on a quick call with you, you can ping me here: https://twitter.com/li_hbr

**Comment by rahulkumarsingh73690** [comment]
> Thanks again! Nothing related to the browser here. 🤔 Starting to get a bit clueless!
> 
> Can you try monitoring XHR requests in the network tab of the devtool? Trying to identify which request fails, sharing its method (GET/POST/etc.), request/response headers and status would be helpful! Might sound a bit daunting, if you want to I'm happy to jump on a quick call with you, you can ping me here: https://twitter.com/li_hbr

Please check twitter

**Comment by lihbr** [comment]
Here's a quick follow up of our discussion on Twitter:

After some time we noticed that that the value of `websitePreviewId` was getting stripped on Rahul's website, leading to the issue:
![image](https://user-images.githubusercontent.com/25330882/105062097-83e0f480-5a7a-11eb-9177-07f4d0d680f8.png)

We tried to troubleshoot a ton of things to figure that out. Unfortunately, I wasn't able to reproduce this issue on my end and Rahul was not able to attempt a reproduction. Being fine with not having preview for now we're closing this issue.

Happy to reopen it if someone is experiencing the same issue or able to provide a reproduction!

**Comment by lihbr** [comment]
Hey, I was able to reproduce the issue with @phillysnow, finally!

After analyzing working and not-working lock files, turns out the issue was a really murky one due to [@nuxt/ufo@0.5.0](https://github.com/nuxt-contrib/ufo) that was introduced in [nuxt@2.14.12 patch](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.12) on the 16th of December.

Everyone that installed this patch before the 6th of January might encounter it.

After this date, the bug got fixed as of [@nuxt/ufo@0.5.3](https://github.com/nuxt-contrib/ufo/blob/main/CHANGELOG.md) release.

If you're encountering this bug, to fix the issue you need to run `$ npm update` or `$ yarn upgrade` in order to update `@nuxt/ufo` to version `0.5.3` or higher, let us know if the bug persists.

Cheers~!

**Comment by rahulkumarsingh73690** [comment]
Let me check this @nuxt/ufo

**Comment by rahulkumarsingh73690** [comment]
Finally, after deleting the package-lock.json and node_modules folder and after a fresh install everything is working fine.

All credit goes to @lihbr
