### ISSUE TITLE
Have to hard refresh the page to get $prismic.api working

### ISSUE THREAD

**Issue by hatrena** [nuxt-community/prismic-module#117]
I am testing Prismic on my localhost and facing an issue where I have to refresh the page so that `$prismic.api` get to work, otherwise, if I navigate through `NuxtLink`i receive `$prismic.api.getByUID is not a function` error message.

I also used the javascript package to fetch documents, same problem. I also noticed the generic API call to Prismic gets blocked and showing `Referrer Policy: strict-origin-when-cross-origin` and also i get `Failed to init Prismic API, preventing app fatal error.`

sample code:
```
const data = await $prismic.api.getByUID(
      'category',
      'uid'
    )
```

Can you please help me on this?

**Comment by hatrena** [comment]
strange, the issue was caused by a chrome extension adblocker. I disabled the extension and everything seems working.

**Comment by lihbr** [comment]
Glad you figured it out @hatrena! Are you able to share the extension causing this issue? I'd be curious to have a look :eyes:

**Comment by hatrena** [comment]
Hi @lihbr , yes that is the famous extension: https://chrome.google.com/webstore/detail/adblock-%E2%80%94-best-ad-blocker/gighmmpiobklfepjocnamgkkbiglidom

Maybe if you have the problem, it's a good idea to mention it in the docs. Thanks 👍
