### ISSUE TITLE
Define v1.0.0 Release

### ISSUE THREAD

**Issue by jamespegg** [nuxt-community/prismic-module#12]
The library is still technically in a pre-release state, which means in theory the API could change between releases (although I'm sticking strictly to semver...). What are the criteria for moving to a v1.0.0 release? Some initial thoughts;

- Overall API stability (are breaking changes being introduced regularly)?
- How many people are using the library currently?
- Important features that need to be included?

# Roadmap
- [ ]  #13 Private Repositories
- [ ]  #21 Slice Component
- [ ]  #20 Generate sitemap.xml

**Comment by glenndevenish** [comment]
Fixing #13 (private repositories) would be nice

**Comment by jamespegg** [comment]
> Fixing #13 (private repositories) would be nice

@glenndevenish Good shout, I've added it to the list. Anything else you can think of that would be useful?

**Comment by glenndevenish** [comment]
Not sure at the moment... I'm in the process of making a prismic-nuxt app, so if I come across anything I'll let you know!
