### ISSUE TITLE
Preview page mode

### ISSUE THREAD

**Issue by hungvo-madison** [nuxt-community/prismic-module#124]
Hi
The nuxtJS does not currently support preview in when generating a static site? is this right?
I'm building an app with target static but not working.
Have you guys any suggest? ^^

**Comment by lihbr** [comment]
Hey @hungvo-madison, thanks for contributing!

I'm not sure I fully got your issue, Prismic previews should be working fine with static sites using this module.

If you have trouble setting up those I'd suggest you using our [community forum](https://community.prismic.io). If you feel you found a bug please provide more information here (reproduction, package.json, nuxt.config.js, etc.), I'll do my best to help you~ :relaxed:

Cheers!

**Comment by lihbr** [comment]
Closing this issue since stale, feel free to reopen if needed!
