### ISSUE TITLE
Access Token for Private Repositories?

### ISSUE THREAD

**Issue by cfofiu** [nuxt-community/prismic-module#13]
Thanks for making this available.
Quick question: how to use access token for private repositories?

**Comment by Atinux** [comment]
Actually, one quick fix would be to allow the accessToken only in `dev` mode :)

**Comment by sergiocerrutti** [comment]
Hi @jamespegg, do you know if there is any way to do this even with a fix? Thanks.

**Comment by hypervillain** [comment]
Hey @sergiocerrutti you can now pass an `apiOptions` param to the module, that would then be passed to the Prismic API initialisation:
```javascript
['@nuxtjs/prismic', { apiOptions: { accessToken: 'xxx' } }]
````
but as James suggested the module runs on both client and server sides.
