### ISSUE TITLE
Can't regenerate slice screenshot (Puppeteer)

### ISSUE THREAD

**Issue by gmirmand** [nuxt-community/prismic-module#133]
Hey !

I have a problem to regenerate the screenshot of my slices from the slicemachine. The first generation seems to work fine, but when I want to re-generate it the sm crashes and I get this error
```bash
[slice-machine] Error: Could not find browser revision 818858. Run "PUPPETEER_PRODUCT=firefox npm install" or "PUPPETEER_PRODUCT=firefox yarn install" to download a supported Firefox browser binary.
    at ChromeLauncher.launch (/Users/gmirmand/Sites/webqam/node_modules/puppeteer/lib/cjs/puppeteer/node/Launcher.js:79:23)
    at handler (/Users/gmirmand/Sites/webqam/node_modules/slice-machine-ui/server/api/screenshot.js:29:19)
    at /Users/gmirmand/Sites/webqam/node_modules/slice-machine-ui/server/api/index.js:20:19
```
Obviously, running the commands quoted in the error does not solve the problem

node: `12.21`
`"slice-machine-ui": "^0.0.45",`
`"@nuxtjs/storybook": "^3.3.1",`

Thanks in advance for your help ! :)

**Comment by lihbr** [comment]
Hey @gmirmand, sorry for the lack of reactivity back then.

- Are you still experiencing the issue?
- Can you try updating your dependencies (cleaning node_modules, lock file and installing again)?

If you're still experiencing the issue after that can you share your system details (yarn or npm version, nuxt version, Nuxt config file, anything that could be helpful for us to debug!)

**Comment by lihbr** [comment]
Closing as stale, Slice Machine screenshot mechanism has also been reworked since then.

I'm sorry again for the lack of reactivity, thanks for your contribution!
