### ISSUE TITLE
Static site Prismic page previews don't work when base is set

### ISSUE THREAD

**Issue by andypattenden** [nuxt-community/prismic-module#139]
When using a `base` in the router configuration and serving a statically generated site, the base is not prefixed to URLs when trying to preview a page from Prismic.

When the site is served using the nuxt server, the previewed URL correctly has the prefix due to the router prefixing the url with the `base`.

I believe this is caused by this https://github.com/nuxt-community/prismic-module/blob/master/templates/plugins/prismic.js#L87 where the URL is just what is returned from the link resolver.

This _could_ be resolved by adding a redirect but we have other sites served on the same domain but differing base paths.

### Versions
- nuxt: v2.15.6
- @nuxtjs/prismic: v1.3.0
- node: v14.17.0

### Reproduction

<details open>
<summary>Additional Details</summary>
<br>
For example, a site which is accessed at http://example.com/us/ and previewing a page with the document ID of `example-page`

#### Prismic Preview Config

- Site name: Local Development
- Domain: `http://localhost:3000`
- Link Resolver: `/us/preview`

#### Nuxt config

```javascript
{
  target: 'static',
  modules: {
    '@nuxtjs/prismic'
  }
  prismic: {
    endpoint: '<endpoint>',
    linkResolver: '@/plugins/prismic/LinkResolver', // Follows same logic as https://prismic.io/docs/technologies/link-resolver-nuxtjs#define-the-link-resolver-function
    apiOptions: {
      accessToken: '<token>',
    },
  },
  router: {
    base: '/us/'
  },
  generate: {
    fallback: true,
    dir: 'dist/us',
  },
}
```
</details>

### Steps to reproduce
1. Generate the site with `npm run generate`
2. Start a server serving from the `dist` dir (I had to use [http-server](https://github.com/http-party/http-server) with this command `http-server -p 3000 -c-1 --proxy http://localhost:3000/us/404.html\?`)
3. Go to the document to be previewed in Prismic and preview with the Local Development option, e.g. for page with document ID `example-page`

### What is Expected?
1. Preview page opens at `http://localhost:3000/us/preview`
2. Preview page updates URL to http://localhost:3000/us/example-page

### What is actually happening?
1. Preview page opens at `http://localhost:3000/us/preview`
2. Preview page updates URL to `http://localhost:3000/example-page`

**Comment by lihbr** [comment]
Hey! Thank you so much for contributing! I'm having a look at your PR this afternoon, if everything's ok I'll roll a patch ☺️, continuing the discussion in #140

> Start a server serving from the dist dir (I had to use http-server with this command http-server -p 3000 -c-1 --proxy http://localhost:3000/us/404.html\?)

Just in case you don't know, now we can use `nuxt start` / `npm run start` to just serve assets from the `dist` directory when using Nuxt static mode~

**Comment by andypattenden** [comment]
Great, thanks!

>Just in case you don't know, now we can use nuxt start / npm run start to just serve assets from the dist directory when using Nuxt static mode~

I did try this but with the `us` subdirectory in the `dist` dir, Nuxt was throwing an error for me. I'll take another look and see if I can figure it out.

**Comment by lihbr** [comment]
Oh, indeed, might have a bug there 🕵️‍♀️
