### ISSUE TITLE
Use prismic-nuxt in nuxt config

### ISSUE THREAD

**Issue by MarineLB** [nuxt-community/prismic-module#14]
Hello! Is it possible to use $prismic to query data in nuxt config, to generate the routes dynamically ?
I have this, which does not yet work.

```
generate: {
    routes: function () {
      return $prismic.api.query(Prismic.Predicates.at('document.type', 'project'))
        .then((res) => {
          return res.results.map((project) => {
            return {
              route: '/project/' + project.uid,
              payload: project
            }
          })
        })
    }
  },
```

**Comment by jamespegg** [comment]
Hi @MarineLB, unfortunately it's not possible to generate dynamic routes in `nuxt.config.js` like that right now, but you can always use standard nuxt dynamic routes: https://nuxtjs.org/guide/routing#dynamic-routes

I guess you're looking to generate the routes and then host the static files?

**Comment by CalebKester** [comment]
@MarineLB here's what I use in my site. I put this at the top of my nuxt.config.js
```const Prismic = require('prismic-javascript');
const prismicEndpoint = 'https://<REPOSITORY>.cdn.prismic.io/api/v2';

// TODO: Factor in Page Size > 100
const routes = () =>
	Prismic.getApi(prismicEndpoint)
		.then(api =>
			api.query(Prismic.Predicates.at('document.type', 'page'), {
				pageSize: 100,
				orderings: '[my.layout.uid]',
			}),
		)
		.then(res => {
			if (res.total_pages > 1) {
				console.warn('we have more than 100 pages, fix it');
				process.exit(1);
			}
			return [
				'/',
				...res.results.map(page => `${page.uid.replace(/_/g, '/')}/`),
				'404',
			];
		});
```

And then at inside my module.exports I have: ```
	generate: {
		fallback: 'app.html',
		routes,
	},```
