### ISSUE TITLE
Problem with query predicates when zero documents are created 

### ISSUE THREAD

**Issue by RAHMANIABOUBEKER** [nuxt-community/prismic-module#143]
### Versions

- nuxt: v2.15.6
- @nuxtjs/prismic: v1.3.1
- node: v14.16.1

### Steps to reproduce
 Create content Type in Prismic and do not create documents for this content type.
Try to query document with a predicate by field
### What is Expected?

I am expecting to get the same result when any document of this type exists.

### What is actually happening?

[function at(..)] unexpected field 'my.article.categorie' on line:1 col:45 in query '[[at(document.type, \"article\")][at(my.article.categorie, \"YGzcjhIAACwAfXQ_\")][any(my.article.type, [\"article\",\"video\",\"podcast\"])]]'\n[[at(document.type, \"article\")][at(my.article.categorie, \"YGzcjhIAACwAfXQ_\")][any(my.article_investir.type, [\"article\",\"video\",\"podcast\"])]]\n                                            ^\n

**Comment by lihbr** [comment]
Hey, thanks for the report! Closing in favor of https://github.com/prismicio/prismic-javascript/issues/169
