### ISSUE TITLE
Bump prismic-dom from 2.2.5 to 2.6

### ISSUE THREAD

**Issue by octo-topi** [nuxt-community/prismic-module#147]
### Is your feature request related to a problem? Please describe.
A bugfix has been released [in prismic-dom ](https://github.com/prismicio/prismic-richtext/issues/47) 2.6

### Describe the solution you'd like
Bump [current dependency ](https://github.com/nuxt-community/prismic-module/blob/master/package.json#L33)from 2.2.5 to 2.6

**Comment by lihbr** [comment]
Hey, as explained, just running `yarn upgrade` or `npm update` should bump `prismic-dom` for you ☺️ (and if not, try removing your `node_modules` and lock file to force an update)

This package uses the caret (`^`) semver version range for `prismic-dom`. This means that upon installation (or update) it will install the most recent version from the said range (`^2.2.5`), here the latest version we published today: `^2.2.6`.

I will perform dependency maintenance later this month, in the meantime the above already get you covered ☺️

Let us know if anything!
