### ISSUE TITLE
​ Prismic preview toolbar overflows on the right on mobile, cant close preview

### ISSUE THREAD

**Issue by gabrielsze** [nuxt-community/prismic-module#162]
![Screenshot 2022-05-21 at 12 20 30 PM](https://user-images.githubusercontent.com/46477732/169804856-e99b0f19-1e18-4297-a47a-bee4767197cb.png)

### Versions

- nuxt-edge: v2.16.0
- @nuxtjs/prismic: v1.2.6
- node: v14.18.0

### Reproduction

Currently dont have a repro on this, wondering if it's because of my CSS stylesheet, seems to have encountered this really early on.

### What is Expected?

I should be able to see the close preview X on the mobile.

### What is actually happening?

It's being overflowed on the right. The preview functionality works well for me, but I'm wondering if I'm the only one facing this issue on mobile where I can't click the close preview button.

Here's how it looks for me, I've tried to edit by using global CSS but it doesn't work because the CSS is injected via a shadow root.

Is there anything I can do to reveal the X button to close my preview on mobile?

**Comment by lihbr** [comment]
Hey there, thanks for opening an issue!

This is indeed a known issue of the toolbar, we're tracking it internally.

In the meantime preview can be closed by switching to paysage mode.

I'll let you know when we have progress on it :relaxed:
