### ISSUE TITLE
Preview error on nuxt 3 SSR using v3 module

### ISSUE THREAD

**Issue by eveningforgery** [nuxt-community/prismic-module#164]
Hello there, I'm having issues with the preview on nuxt 3 & @nuxtjs/prismic v3. 

I configured the preview in prismic as such:

Domain:
http://localhost:3000
Link resolver:
/preview

When launching the preview, the server throws a 500 error, `useHead is not defined`.

I also deployed & configured it on Netlify, and I'm getting the same error in a live environment.

I also tried my luck making a custom preview file `pages/preview.vue` but I'm getting the same exact error.

### Versions

- nuxt: 3.0.0-rc.4 
- @nuxtjs/prismic: 3.0.0-alpha.5 
- node: 16.14.2

<details open>
<summary>Additional Details</summary>
<br>

`nuxt.config.ts`
```ts
import { defineNuxtConfig } from 'nuxt'
import svgLoader from 'vite-svg-loader'

// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  buildModules: [
    '@pinia/nuxt',
    '@vueuse/nuxt',
    '@intlify/nuxt3',
  ],
  
  modules: [
    '@nuxtjs/tailwindcss',
    '@nuxtjs/prismic',
  ],

  prismic: {
    endpoint: 'xxxx',
  },

  intlify: {
    localeDir: 'locales',
    vueI18n: {
      locale: 'en-gb',
      fallbackLocale: 'en-gb',
    }
  },

  components: {
    dirs: [
      { path: '~/components', global: false},
      { path: '~/slices', global: false },
    ],
  },

  runtimeConfig: {
    public: {
    }
  },

  vite: {
    plugins: [
      svgLoader(),
    ]
  }
})

```

`nuxt dev` console
```
  [Vue warn]: Unhandled error during execution of setup function 
    at <Preview onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > key="/preview" >
  [nuxt] [request error] useHead is not defined
    at setup (./.nuxt/dist/server/server.mjs:22715:1)  
    at _sfc_main.setup (./.nuxt/dist/server/server.mjs:22755:23)  

```

`.nuxt/dist/server/server.mjs`
```javascript
const _sfc_main = {
  __name: 'preview',
  setup(__props, { expose }) {
  expose();

useHead({ // <---- Error thrown here
	title: 'Prismic Preview - Loading'
})

// TODO: refactor into simple hook
const { client, options: { linkResolver } } = usePrismic()
const { push } = useRouter()
__vite_ssr_import_0__.onMounted(async () => {
	const redirectURL = await client.resolvePreviewURL({
		linkResolver,
		defaultURL: '/'
	})

	push(redirectURL ?? '/')
})
```

</details>

### Steps to reproduce
- Install and configure `@nuxtjs/prismic` in `nuxt.config.ts`
- Setup preview on prismic
- Click the preview icon in UI
- Error `useHead is not defined` shows up

### What is Expected?
Preview working properly

### What is actually happening?
Error 500
`useHead is not defined`

**Comment by lihbr** [comment]
Hey there, thanks for opening an issue!

Can you update to the latest RC (`nuxt@3.0.0-rc.4` as of today) and try again?
If I remember correctly `useHead` was introduced to replace `useMeta` (which is now deprecated) for the first RC ☺️

Let me know!

**Comment by lihbr** [comment]
OK, question: In development (outside of previews), are you able to go to `/preview` without any error?

**Comment by lihbr** [comment]
Alright, should be fixed in `3.0.0-alpha.6`, let me know ☺️

**Comment by lihbr** [comment]
Great! You should at least see the toolbar if you're logged in to Prismic. Content not updating in every case is part of it indeed yes ^^' I'll work on it soon

**Comment by renardsas** [comment]
Hey @lihbr  ,

### Versions
- nuxt: 3.0.0-rc.4
- @nuxtjs/prismic: 3.0.0-alpha.6
- node: 16.15.0

Toolbar doesn't show up because it is not loaded.
File : 
[https://github.com/nuxt-community/prismic-module/blob/master/src/module.js](url)

``` js
// Add toolbar
const repositoryName = isRepositoryEndpoint(mergedOptions.endpoint)
? getRepositoryName(mergedOptions.endpoint)
: mergedOptions.endpoint
nuxt.options.head ||= {}
nuxt.options.head.script ||= []
nuxt.options.head.script.push({
src: `https://static.cdn.prismic.io/prismic.min.js?repo=${repositoryName}&new=true`
})
```

It's working when I replace **nuxt.options.head.script** with **nuxt.options.app.head.script**
[https://v3.nuxtjs.org/api/configuration/nuxt.config#head](url)

**Comment by lihbr** [comment]
Great catch, thank you so much! TypeScript got me wrong here between Nuxt 3 & Nuxt 2 types, my bad 🤦‍♀️

Just released this fix as part of `3.0.0-alpha.7`, there are still some gotchas with previews through due to the lack of [preview mode](https://nuxtjs.org/docs/features/live-preview#preview-mode) in Nuxt 3. This can be worked around however with some tricks so I'll implement that in July ☺️

Thank you so much for trying Nuxt 3 and the new Prismic module ❤️

**Comment by lihbr** [comment]
Actually nevermind, I felt inspired tonight so I released `3.0.0-alpha.8` which should bring you full preview support 🎉

There might be some gotchas left, especially with SSR, so let me know if you encounter anything unexpected, but previews are here for real 🙌

![Champagne gif](https://i.giphy.com/media/nV92wySC3iMGhAmR71/giphy.webp)

If that's OK with you I'm closing this issue as I think the initial issue has been answered ☺️

**Comment by renardsas** [comment]
I just install the last version and I have this error :
![Capture](https://user-images.githubusercontent.com/7579904/176966718-699c466d-3bfd-4086-be18-85435a45cfea.PNG)

I have no other module, just @nuxtjs/prismic.
Without @nuxtjs/prismic, no error when nitro build.

**Comment by lihbr** [comment]
Of course, thankfully releases are free, should be good in `3.0.0-alpha.9` Thanks for the heads up again 🙏

If you're curious about what it was, basically auto imports don't work (yet) in modules (oddly they work in the module playground or with `yarn link`, but not once shipped as a package), so while they are typed as "here" we have to import them still ^^

**Comment by lihbr** [comment]
Alright, `3.0.0-alpha.10`

**Comment by renardsas** [comment]
Thanks for the follow up and the commits 🙏🙏🙏🙏

And also a big thank you for this article:
https://lihbr.com/blog/pushing-nuxt-js-static-generation-one-step-further
At the time, this approach provided excellent performance

**Comment by lihbr** [comment]
You welcome, thanks! ☺️

**Comment by renardsas** [comment]
Small improvement:
```js
// Current
nuxt.options.app.head.script.push({
   src: `https://static.cdn.prismic.io/prismic.min.js?repo=${repositoryName}&new=true`
})

// Add defer and async to script
nuxt.options.app.head.script.push({
   src: `https://static.cdn.prismic.io/prismic.min.js?repo=${repositoryName}&new=true`,
   defer: true,
   async: true
})
```

Maybe also a way to activate the preview but without loading the script ?
```js
prismic: {
    preview: {
        url: '/preview',
        script : false
  }
```
I load it only when a certain cookie is present. I do this because otherwise all users logged in or not have to download the script + ifram + source font pro ...
![Capture](https://user-images.githubusercontent.com/7579904/176971578-965c25a8-fc9c-4be2-a834-627b237e3cdd.PNG)

**Comment by lihbr** [comment]
Sure, will add that to my backlog ☺️ Great ideas!

If you'd like to contribute further PRs are very welcome too ☺️
