### ISSUE TITLE
TypeError: Only absolute URLs error

### ISSUE THREAD

**Issue by paulmendrik** [nuxt-community/prismic-module#39]
Hi,

I get a TypeError: Only absolute URLs are supported error after installing and configuring the plugin using your instructions.
Any ideas why ?

Thanks

**Comment by Atinux** [comment]
Hi @french-menders 

Could you create a reproduction with https://template.nuxtjs.org please?

**Comment by hypervillain** [comment]
It could be a simple configuration problem, double-check the `modules` property of your config file. Should be something like this:

```javascript
modules: [
    ['@nuxtjs/prismic', {
      endpoint: 'https://dkdddddddd.cdn.prismic.io/api/v2',
      ...
    }]
]
````

If I remember correctly, I had this error when I accidentally got rid of the first array level
