### ISSUE TITLE
Running Nuxt generate may delete preview page

### ISSUE THREAD

**Issue by hypervillain** [nuxt-community/prismic-module#48]
I've been trying to use `nuxt generate` to bundle my app, but realised that the prismic-preview page is replaced if a dynamic page `Pages/_uid.vue` is declared.

For example, given this router:

```javascript
routes: [{
    path: "/",
    component: _111d55e9,
    name: "index"
  }, {
    path: "/:uid",
    component: _928d536c,
    name: "uid"
  }, {
    path: "/preview",
    component: _a600f166,
    name: "prismic-preview"
  }]

````

Nuxt will indeed generate a page at "/preview" but will try to use the "uid" template,
resulting in a 404

**Comment by Atinux** [comment]
Nice catch @hypervillain 

Fixed in https://github.com/nuxt-community/prismic-module/commit/78c28baa6aa16f255f6886d6451960ba227c0be3 and released in `v1.0.2`
