### ISSUE TITLE
Allow option to define linkResolver/htmlSerializer paths in config (and update docs)

### ISSUE THREAD

**Issue by haversnail** [nuxt-community/prismic-module#49]
Somewhat related to #28:

Although it seems you can in fact set a `linkResolver` and/or `htmlSerializer` directly in the module options object, this option isn't actually documented (and, on a side note, seems to yield some funky results when you check out the output in `.nuxt/prismic`, depending on whether you define them directly in the config or import them from elsewhere). However, IMO this approach makes more sense for the developer instead of prescribing where these functions should live in their project (i.e. `~/app/prismic`). My suggestion would be to officially allow the following options:
1. Define a `linkResolver` and `htmlSerializer` directly in the module options object (seems to work, just needs to be documented)
2. Specify a path to the `linkResolver` and `htmlSerializer` — for example:
```js
// nuxt.config.js
prismic: {
  endpoint: 'https://foo.cdn.prismic.io/api/v2',
  linkResolver: '~/plugins/prismic/link-resolver.js',
  htmlSerializer: '~/plugins/prismic/html-serializer.js'
}
``` 
I think this approach would be the most idiomatic and would give developers better flexibility in terms of how they organize their codebase. 😄 

Also happy to help contribute if needed. Thanks in advance! 👍

**Comment by hypervillain** [comment]
Hey @haversnail,

thanks for reporting this! From my understanding of the module, `~/app/prismic` is not a folder you're supposed to create by yourself. It is populated inside the `.nuxt` app, generated by the module. But you are 100% right when you say it should be documented, I'll add this to our tasks list.

Considering handling files, IMO it does not offer more than passing the function. You could easily write this instead, and even more than what the module could safely do for you:

```javascript
import config from '@/path/to/config'

prismic: {
  endpoint: config.endpoint,
  ...
}
````

Then you'd be free to store these anywhere you want ✌️

Happy to discuss it further of course

**Comment by Atinux** [comment]
Hi @haversnail 

Indeed, this `app/` is a new standard we are trying to push with Nuxt (early stage_ to allow users to easily overwrite JS file that are used by modules but can be overwritten. This allow to make the `nuxt.config.js` smaller but also avoiding a full server reload in development for faster development experience.

Anyway, I release [v1.1.0](https://github.com/nuxt-community/prismic-module/releases/tag/v1.1.0)  that allows you to give a custom path to `linkResolver` and `htmlSerializer` as well as updated the [documentation](https://prismic-nuxt.js.org/docs/configuration).

Keep rocking guys 💚

**Comment by haversnail** [comment]
Ah, I see — that makes sense why `~/app` would be the default then. Thanks for the clarification, and thanks for getting that change out so quickly! 👏
