### ISSUE TITLE
Render whole single type page

### ISSUE THREAD

**Issue by defudef** [nuxt-community/prismic-module#50]
Hi,
I'm using your module in the Vue project and I had to render recursively each single type page component. The problem is, I cannot just put the whole document response to any helper method because it causes errors.

The good news is I actually made an implementation for this. Can I create a PR for you guys?

**Comment by hypervillain** [comment]
Hey @defudef 👋

I'm not sure I fully understand what you're trying to achieve, but we'd be happy to read your code. You can fork this repo and submit a PR (you don't need to wait for it to be 100% done of course)
