### ISSUE TITLE
How to access $prismic.api from nuxtServerInit

### ISSUE THREAD

**Issue by timdiacon** [nuxt-community/prismic-module#54]
Awesome work on this module so far!

Before switching to the module I've been making a call to the api of getSingle in my nuxtServerInit to load in my site navigation. Prismic doesn't seem to exist in the context passed to the nuxtServerInit method so just wondering how I would go about accessing it or calling the api?

**Comment by timdiacon** [comment]
I am an idiot. $prismic is available in the context passed to nuxtServerInit just as it is in asyncData... I just had the module configured incorrectly in my nuxt.config

**Comment by jeerbl** [comment]
@timdiacon How did you configure the module in `nuxt.config` to access `$prismic` in `nuxtServerInit` then? Can't seem to work it out

**Comment by jeerbl** [comment]
Just figured it out, it was the second parameter of `nuxtServerInit` :)
