### ISSUE TITLE
Disable the toolbar/edit button

### ISSUE THREAD

**Issue by adrianocr** [nuxt-community/prismic-module#57]
Short of hiding the button via css I don't see a way to disable the prismic toolbar / edit button. I dug through the code and I didn't even really see anything related to that button other than what seems to be what injects the script at the bottom of .nuxt/prismic/plugins/prismic.js:

```
  if (process.client) {
    window.onNuxtReady(() => {
      const script = document.createElement('script')

      script.src = '//static.cdn.prismic.io/prismic.min.js?repo=XXXXXXXXXXXXXXX&new=true'
      document.body.appendChild(script)
    })
  }
```

How can I disable the button, at least on production builds?

**Comment by sergaks** [comment]
Created pull request for the same issue https://github.com/nuxt-community/prismic-module/pull/58
