### ISSUE TITLE
Breaking Error when Previewing

### ISSUE THREAD

**Issue by egstad** [nuxt-community/prismic-module#74]
When attempting to preview a draft from Prismic, this error is thrown:

`WARN  previewSession function is deprecated in favor of getPreviewResolver function.`

As a result, the preview is aborted and Prismic's master ref is used.

Environment:
- `nuxt 2.12.2`
- `@nuxtjs/prismic 1.2.1`

**Comment by jaggdl** [comment]
Try deleting your cookies. That worked for me.

**Comment by egstad** [comment]
Tried it, but previews still aren't working. 😢

**Comment by hypervillain** [comment]
Hey @egstad can you give a try to #80 ?

**Comment by egstad** [comment]
@hypervillain - that did the trick! Error is now gone.

**Comment by hypervillain** [comment]
Awesome. Expect it to be merged in the coming days ✌️
