### ISSUE TITLE
Replace deprecated 'previewSession' method with 'getPreviewResolver'

### ISSUE THREAD

**Issue by phillysnow** [nuxt-community/prismic-module#83]
We need to replace the previewSession method used for parsing preview cookies shown here:
https://github.com/nuxt-community/prismic-module/blob/master/src/templates/plugins/prismic.js

With the new getPreviewResolver (available with `prismic-javascript v.3.0.1`) which is documented here:
https://prismic.io/docs/vuejs/beyond-the-api/in-website-preview#18_0-processing-the-preview-token-with-getpreviewresolver-method

**Comment by hypervillain** [comment]
#80 should solve this
