### ISSUE TITLE
Allow specifying a release ref in the api options

### ISSUE THREAD

**Issue by phillysnow** [nuxt-community/prismic-module#89]
It would be nice to specify a release ref instead on the default master ref in the apiOptions when testing content from a release. It would look something like this:
```
prismic: {
        endpoint: "https://repo-name.cdn.prismic.io/api/v2",
        linkResolver: "@/plugins/link-resolver",
        htmlSerializer: "@/plugins/html-serializer",
        apiOptions: {
            ref: "XutFvRIAAL0EkMA0~XutfQhIAAPgakTPC"
        }
    }
```

This workaround for now is to specify the ref in the options of each api call.

Here's a link to the discussion on the forum:
https://community.prismic.io/t/apioption-ref-does-not-seem-to-work-in-nuxt-config-js/906

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. This will be part of the module v2 after we're done refreshing @prismicio/client: https://github.com/prismicio/prismic-javascript/issues/163

**Comment by lihbr** [comment]
The new version of the module targetting Nuxt 3 (https://v3.prismic.nuxtjs.org) uses the aforementioned new client that allows being inited with a specific ref 🎉

https://prismic.io/docs/technical-reference/prismicio-client#setup-methods
