### ISSUE TITLE
Package calls a prismic script  on 'nuxt generate'

### ISSUE THREAD

**Issue by ValdoGhafoor** [nuxt-community/prismic-module#91]
## Expected Behavior
When using nuxt generate, all content has been already fetched, therefore there should be no trace of prismic on static website

## Current Behavior
Api calls are made on load. (On my production hosting)

<img width="646" alt="Capture d’écran 2020-07-24 à 14 06 51" src="https://user-images.githubusercontent.com/7875009/88389797-742c7000-cdb7-11ea-935c-27ba1b341ea3.png">

Is this intended ?

**Comment by kolbykruger** [comment]
Correct me if I am wrong, but I believe this is used for the Prismic Toolbar (the front-end edit button that appears in the bottom left when you are logged-in to the Prismic dashboard.

**Comment by lihbr** [comment]
@kolbykruger you're correct, those calls are in order:

1. Prismic API client initing itself
2. Toolbar script being loaded
3. Toolbar iframe being loaded

They are required for the preview feature to work. Let me know @ValdoGhafoor if you have other concerns regarding those otherwise I'll close the issue 🙂

**Comment by ValdoGhafoor** [comment]
Is there a way to disable the toolbar ?
Our editors uses the toolbar on our preprod environnement and we would like to get rid of unnecessary requests in production.

**Comment by lihbr** [comment]
Yup, by setting `preview` option to false in the module option:
```
{
  /* ... */
  preview: process.env.NODE_ENV !== "production"
}
```

+ I'll work on an RFC next week to provide an option to load the preview script only when needed~ (TBD)

**Comment by Jeffreykvo** [comment]
Any updates?
Prismic is amazing and it would be even more amazing if i could get rid of this unnecessary request.
Thanks i advance :)

**Comment by lihbr** [comment]
Hey, glad you're enjoying Prismic! We're working on an update of the toolbar right now (in QA) that will allow some exciting things with this module and we'll move forward toward that issue right after, probably rolling a major for it 🙂

**Comment by lihbr** [comment]
Closing in favor of #134 (I explained the envisioned workaround there), we should fix that soon!
