### ISSUE TITLE
Set endpoint programmatically

### ISSUE THREAD

**Issue by jameshhood** [nuxt-community/prismic-module#94]
So my challenge is to be able to make the endpoint configurable for my app. Right now you can do it in the config during build time. If I need to change this endpoint without bringing down the app I need to be able to set it via an environment variable or programmatically on say nuxtServerInit.

How do I go about doing this?

(edit, see: https://github.com/nuxt-community/prismic-module/issues/94#issuecomment-670192228 for Axios default like)

**Comment by lihbr** [comment]
Hey James, thanks for contributing!

I'm not 100% sure of what you're trying to achieve so let me know. If you're looking to set the endpoint according to an environment variable you can do so in you're `nuxt.config.js` file:

```javascript
export default: {
  prismic: {
    endpoint: process.env.PRISMIC_ENDPOINT
  }
}
```

Although doing it this way the endpoint will end up being set at build time. If you want to change your endpoint at runtime I'm afraid you'll need to get away of `this.$prismic.api` and init your API through `prismic-javascript` directly, see [here](https://prismic.io/docs/javascript/getting-started/integrating-with-an-existing-javascript-project#3_0-3.-connect-to-the-api-and-query-your-content).

**Comment by jameshhood** [comment]
@lihbr Yeah so I have an ecommerce app that I've written and have multiple customers that use it all wanting their own branding and tweaks. So I would have a prismic repo for each one of them and that's where being able to tweak a setting somewhere would be nice and not having to build it in. I've done the environment variable for now, but hopefully this will be functionality available in the future; Kind of like axios

**Comment by lihbr** [comment]
Oh ok I understand better, well to me the environment variable way sounds like the de facto way of doing it, can you enlighten me about the way Axios is doing it though? Glad you found a way around that anyway 🙂

**Comment by jameshhood** [comment]
I was just referring to Axios, because with their API, they have a method to set the default endpoint for requests. Then every time you do a get or post, you just have to supply the endpoint. 

For Instance:
```
$axios.defaults.baseURL = 'www.google.com'
$axios.get('/someendpoint', {
     params: {...}
})
```
this would automatically hit `www.google.com/someendpoint` with the query parameters

Also in the nuxt config, they have the same deal
```
// nuxt.config.js
module.exports = {
    axios: {
        baseURL: process.env.API_URL || 'www.google.com'
    }
}
```
So you can just set it in the config, or if you have a need to dynamically change it for what ever reason, you can do so via the defaults object

**Comment by lihbr** [comment]
Oh I see, thanks for sharing we'll see if we can implement that at some point! 🙂

**Comment by jevillard** [comment]
Hello,

You can also add the ability to configure the endpoint at runtime as in axios module (see https://axios.nuxtjs.org/options#runtime-config)

Use case possible: build only a docker image and inject the endpoint as an environment variable at runtime time so when using the `nuxt start` and not when using `nuxt build`

Thanks

**Comment by lihbr** [comment]
Hey, thanks for your input @jevillard, definitely a legit usage! We should start working on some enhancements for the module soon! ☺️

**Comment by lihbr** [comment]
*Update `05/04/2021`:*
1. I attempted to support runtime config in #137. Unfortunately, this would introduce breaking changes for some people. Support for runtime config will be added in v2~

**Comment by michael-observerly** [comment]
Just to add potentially a small modicum of weight for this feature - we currently are migrating a Vue project to a Nuxt project.

The issue for us is that we want to set the endpoint not at runtime - but dynamically. We currently see that this.$prismic.apiEndpoint isn't able to be set with out the getter / setter warning. So, potentially the fix could be something as trivial as the following:

```js
apiEndpoint: {
  get(){
    return this.apiEndpoint
  },
  set(apiEndpoint){
    return apiEndpoint
  } 
}
```

**Comment by lihbr** [comment]
Thanks for your input @michael-observerly!

I get the idea although I'm afraid just changing the value of the endpoint won't have any effect on the client instance created previously 🤔

I think for your use case it'll be simpler to just use @prismicio/client alongside the Nuxt module 🤔

**Comment by lihbr** [comment]
`@prismicio/client` has been completely reworked in 2021, changing a client instance endpoint is (still) not possible with it, and I'm not sure this is something we want to introduce. Creating a new instance should remain the preferred way.

With that in mind, I'm closing this issue. However, something I want to explore/support with the [Nuxt 3 module](https://v3.prismic.nuxtjs.org/) is the ability to work with multiple repositories.

I'm really sorry for the false hope here. We're happy to reconsider such features should we get more concrete use cases/demand for it.
